interface for generic mr post processing
aws-solutions-library-samples/osml-model-runner pull request #43
Opened 2023-11-16 21:05 UTC by jtblack-aws

*Issue #, if available:*

*Description of changes:*
Updating model runner to use a more generic "MRPostProcessing" list to read in feature selection/fusion options

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-16 21:39 UTC, drduhe requested changes

2023-11-16 21:39 UTC, drduhe commented on src/aws/osml/model_runner/common/mr_post_processing.py
> +    SOFT_NMS = auto()  # gaussian Soft-NMS (as opposed to linear)
Remove inline comment

2023-11-16 21:39 UTC, drduhe commented on src/aws/osml/model_runner/common/mr_post_processing.py
> +class FeatureDistillationAlgorithm(MRPostProcessingAlgorithm):
Pydoc comment

2023-11-17 02:49 UTC, jtblack-aws commented on src/aws/osml/model_runner/common/mr_post_processing.py
> +    SOFT_NMS = auto()  # gaussian Soft-NMS (as opposed to linear)
moved comment to pydoc string

2023-11-17 02:49 UTC, jtblack-aws commented on src/aws/osml/model_runner/common/mr_post_processing.py
> +class FeatureDistillationAlgorithm(MRPostProcessingAlgorithm):
added pydoc comment

2023-11-17 18:06 UTC, drduhe submitted a review, later dismissed
LGTM

2023-11-20 15:21 UTC, edparris approved these changes

2023-11-20 16:00 UTC, RanbirAulakh commented on src/aws/osml/model_runner/common/mr_post_processing.py
> +    #     return name
Should remove the commented out lines

2023-11-20 17:01 UTC, RanbirAulakh approved these changes

2023-11-20 17:14 UTC, jtblack-aws commented on src/aws/osml/model_runner/common/mr_post_processing.py
> +    #     return name
removed

2023-11-20 17:14 UTC, merged